# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
