# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0002_brew_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
